export const GET_SYSTEM_LOGS = "GET_SYSTEM_LOGS"
export const GET_SYSTEM_LOGS_SUCCESS = "GET_SYSTEM_LOGS_SUCCESS"
export const GET_SYSTEM_LOGS_FAIL = "GET_SYSTEM_LOGS_FAIL"

export const GET_SYSTEM_LOG = "GET_SYSTEM_LOG"
export const GET_SYSTEM_LOG_SUCCESS = "GET_SYSTEM_LOG_SUCCESS"
export const GET_SYSTEM_LOG_FAIL = "GET_SYSTEM_LOG_FAIL"
