// GET requests
export const GET_EMPLOYEES_FOR_NOSI = 'GET_EMPLOYEES_FOR_NOSI'
export const GET_EMPLOYEES_FOR_NOSI_SUCCESS = 'GET_EMPLOYEES_FOR_NOSI_SUCCESS'
export const GET_EMPLOYEES_FOR_NOSI_FAIL = 'GET_EMPLOYEES_FOR_NOSI_FAIL'

export const GET_NOSI_DETAILS = 'GET_NOSI_DETAILS'
export const GET_NOSI_DETAILS_SUCCESS = 'GET_NOSI_DETAILS_SUCCESS'
export const GET_NOSI_DETAILS_FAIL = 'GET_NOSI_DETAILS_FAIL'

// POST, PATCH, PUT & DELETE request
export const POST_NOSI_FOR_APPROVAL = 'POST_NOSI_FOR_APPROVAL'
export const POST_NOSI_FOR_APPROVAL_SUCCESS = 'POST_NOSI_FOR_APPROVAL_SUCCESS'
export const POST_NOSI_FOR_APPROVAL_FAIL = 'POST_NOSI_FOR_APPROVAL_FAIL'
