export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const GET_NON_HRMS_USERS = "GET_NON_HRMS_USERS"
export const GET_NON_HRMS_USERS_SUCCESS = "GET_NON_HRMS_USERS_SUCCESS"
export const GET_NON_HRMS_USERS_FAIL = "GET_NON_HRMS_USERS_FAIL"

export const POST_USER = "POST_USER"
export const POST_USER_SUCCESS = "POST_USER_SUCCESS"

export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"

export const GET_USER_ROLES = "GET_USER_ROLES"
export const GET_USER_ROLES_SUCCESS = "GET_USER_ROLES_SUCCESS"

export const PATCH_USER_ROLES = "PATCH_USER_ROLES"
export const PATCH_USER_ROLES_SUCCESS = "PATCH_USER_ROLES_SUCCESS"

export const USER_API_FAIL = "USER_API_FAIL"
export const RESET_USER_RESPONSE = "RESET_USER_RESPONSE"
