export const GET_QUALIFICATION_STANDARDS_LIST =
  "GET_QUALIFICATION_STANDARDS_LIST"
export const GET_QUALIFICATION_STANDARDS_LIST_SUCCESS =
  "GET_QUALIFICATION_STANDARDS_LIST_SUCCESS"
export const GET_QUALIFICATION_STANDARDS_LIST_FAIL =
  "GET_QUALIFICATION_STANDARDS_LIST_FAIL"

export const GET_POSITION_QUALIFICATION_STANDARDS =
  "GET_POSITION_QUALIFICATION_STANDARDS"
export const GET_POSITION_QUALIFICATION_STANDARDS_SUCCESS =
  "GET_POSITION_QUALIFICATION_STANDARDS_SUCCESS"
export const GET_POSITION_QUALIFICATION_STANDARDS_FAIL =
  "GET_POSITION_QUALIFICATION_STANDARDS_FAIL"

export const PUT_POSITION_QUALIFICATION_STANDARDS =
  "PUT_POSITION_QUALIFICATION_STANDARDS"
export const PUT_POSITION_QUALIFICATION_STANDARDS_SUCCESS =
  "PUT_POSITION_QUALIFICATION_STANDARDS_SUCCESS"
export const PUT_POSITION_QUALIFICATION_STANDARDS_FAIL =
  "PUT_POSITION_QUALIFICATION_STANDARDS_FAIL"

export const RESET_QUALIFICATION_STANDARDS = "RESET_QUALIFICATION_STANDARDS"
