export const GET_OCCUPATIONAL_GROUP_COMPETENCIES =
  "GET_OCCUPATIONAL_GROUP_COMPETENCIES"
export const GET_OCCUPATIONAL_GROUP_COMPETENCIES_SUCCESS =
  "GET_OCCUPATIONAL_GROUP_COMPETENCIES_SUCCESS"
export const GET_OCCUPATIONAL_GROUP_COMPETENCIES_FAIL =
  "GET_OCCUPATIONAL_GROUP_COMPETENCIES_FAIL"

export const GET_AVAILABLE_FUNCTIONAL_COMPETENCIES =
  "GET_AVAILABLE_FUNCTIONAL_COMPETENCIES"
export const GET_AVAILABLE_FUNCTIONAL_COMPETENCIES_SUCCESS =
  "GET_AVAILABLE_FUNCTIONAL_COMPETENCIES_SUCCESS"
export const GET_AVAILABLE_FUNCTIONAL_COMPETENCIES_FAIL =
  "GET_AVAILABLE_FUNCTIONAL_COMPETENCIES_FAIL"

export const ASSIGN_COMPETENCIES_TO_OCCUPATION =
  "ASSIGN_COMPETENCIES_TO_OCCUPATION"
export const ASSIGN_COMPETENCIES_TO_OCCUPATION_SUCCESS =
  "ASSIGN_COMPETENCIES_TO_OCCUPATION_SUCCESS"
export const ASSIGN_COMPETENCIES_TO_OCCUPATION_FAIL =
  "ASSIGN_COMPETENCIES_TO_OCCUPATION_FAIL"

export const UNASSIGN_COMPETENCIES_TO_OCCUPATION =
  "UNASSIGN_COMPETENCIES_TO_OCCUPATION"
export const UNASSIGN_COMPETENCIES_TO_OCCUPATION_SUCCESS =
  "UNASSIGN_COMPETENCIES_TO_OCCUPATION_SUCCESS"
export const UNASSIGN_COMPETENCIES_TO_OCCUPATION_FAIL =
  "UNASSIGN_COMPETENCIES_TO_OCCUPATION_FAIL"

export const RESET_OCCUPATIONAL_GROUP_COMPETENCIES =
  "RESET_OCCUPATIONAL_GROUP_COMPETENCIES"

export const SELECT_OCCUPATION_COMPETENCY_ROW =
  "SELECT_OCCUPATION_COMPETENCY_ROW"
export const UNSELECT_OCCUPATION_COMPETENCY_ROW =
  "UNSELECT_OCCUPATION_COMPETENCY_ROW"
export const RESET_SELECTED_OCCUPATION_COMPETENCY_ROWS =
  "RESET_SELECTED_OCCUPATION_COMPETENCY_ROWS"
