export const GET_COMPETENCY_DOMAINS = 'GET_COMPETENCY_DOMAINS'
export const GET_COMPETENCY_DOMAINS_SUCCESS = 'GET_COMPETENCY_DOMAINS_SUCCESS'
export const GET_COMPETENCY_DOMAINS_FAIL = 'GET_COMPETENCY_DOMAINS_FAIL'

export const GET_CORE_COMPETENCIES = 'GET_CORE_COMPETENCIES'
export const GET_CORE_COMPETENCIES_SUCCESS = 'GET_CORE_COMPETENCIES_SUCCESS'
export const GET_CORE_COMPETENCIES_FAIL = 'GET_CORE_COMPETENCIES_FAIL'

export const GET_FUNCTIONAL_COMPETENCIES = 'GET_FUNCTIONAL_COMPETENCIES'
export const GET_FUNCTIONAL_COMPETENCIES_SUCCESS =
  'GET_FUNCTIONAL_COMPETENCIES_SUCCESS'
export const GET_FUNCTIONAL_COMPETENCIES_FAIL =
  'GET_FUNCTIONAL_COMPETENCIES_FAIL'

export const GET_CROSSCUTTING_COMPETENCIES = 'GET_CROSSCUTTING_COMPETENCIES'
export const GET_CROSSCUTTING_COMPETENCIES_SUCCESS =
  'GET_CROSSCUTTING_COMPETENCIES_SUCCESS'
export const GET_CROSSCUTTING_COMPETENCIES_FAIL =
  'GET_CROSSCUTTING_COMPETENCIES_FAIL'

export const GET_MANAGERIAL_COMPETENCIES = 'GET_MANAGERIAL_COMPETENCIES'
export const GET_MANAGERIAL_COMPETENCIES_SUCCESS =
  'GET_MANAGERIAL_COMPETENCIES_SUCCESS'
export const GET_MANAGERIAL_COMPETENCIES_FAIL =
  'GET_MANAGERIAL_COMPETENCIES_FAIL'

export const GET_PROFICIENCY_KEY_ACTIONS = 'GET_PROFICIENCY_KEY_ACTIONS'
export const GET_PROFICIENCY_KEY_ACTIONS_SUCCESS =
  'GET_PROFICIENCY_KEY_ACTIONS_SUCCESS'
export const GET_PROFICIENCY_KEY_ACTIONS_FAIL =
  'GET_PROFICIENCY_KEY_ACTIONS_FAIL'

export const PUT_MODEL_DETAILS = 'PUT_MODEL_DETAILS'
export const PUT_MODEL_DETAILS_SUCCESS = 'PUT_MODEL_DETAILS_SUCCESS'
export const PUT_MODEL_DETAILS_FAIL = 'PUT_MODEL_DETAILS_FAIL'

export const POST_COMPETENCY_DETAILS = 'POST_COMPETENCY_DETAILS'
export const POST_COMPETENCY_DETAILS_SUCCESS = 'POST_COMPETENCY_DETAILS_SUCCESS'
export const POST_COMPETENCY_DETAILS_FAIL = 'POST_COMPETENCY_DETAILS_FAIL'

export const PUT_COMPETENCY_DETAILS = 'PUT_COMPETENCY_DETAILS'
export const PUT_COMPETENCY_DETAILS_SUCCESS = 'PUT_COMPETENCY_DETAILS_SUCCESS'
export const PUT_COMPETENCY_DETAILS_FAIL = 'PUT_COMPETENCY_DETAILS_FAIL'

export const DELETE_COMPETENCY_DETAILS = 'DELETE_COMPETENCY_DETAILS'
export const DELETE_COMPETENCY_DETAILS_SUCCESS =
  'DELETE_COMPETENCY_DETAILS_SUCCESS'
export const DELETE_COMPETENCY_DETAILS_FAIL = 'DELETE_COMPETENCY_DETAILS_FAIL'

export const UPDATE_KEY_ACTION_DETAILS = 'UPDATE_KEY_ACTION_DETAILS'
export const PUT_KEY_ACTIONS = 'PUT_KEY_ACTIONS'
export const PUT_KEY_ACTIONS_SUCCESS = 'PUT_KEY_ACTIONS_SUCCESS'
export const PUT_KEY_ACTIONS_FAIL = 'PUT_KEY_ACTIONS_FAIL'

export const RESET_COMPETENCY_RESPONSES = 'RESET_COMPETENCY_RESPONSES'
