export const GET_DEPARTMENTS = "GET_DEPARTMENTS"
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS"

export const POST_DEPARTMENT = "POST_DEPARTMENT"
export const POST_DEPARTMENT_SUCCESS = "POST_DEPARTMENT_SUCCESS"

export const PUT_DEPARTMENT = "PUT_DEPARTMENT"
export const PUT_DEPARTMENT_SUCCESS = "PUT_DEPARTMENT_SUCCESS"

export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS"

export const RESET_DEPARTMENT = "RESET_DEPARTMENT"
export const DEPARTMENT_API_ERROR = "DEPARTMENT_API_ERROR"
