export const GET_APPLICANTS = 'GET_APPLICANTS'
export const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS'
export const GET_APPLICANTS_FAIL = 'GET_APPLICANTS_FAIL'

export const GET_QUALIFIED_APPLICANTS = 'GET_QUALIFIED_APPLICANTS'
export const GET_QUALIFIED_APPLICANTS_SUCCESS =
  'GET_QUALIFIED_APPLICANTS_SUCCESS'
export const GET_QUALIFIED_APPLICANTS_FAIL = 'GET_QUALIFIED_APPLICANTS_FAIL'

export const GET_ENDORSED_APPLICANTS = 'GET_ENDORSED_APPLICANTS'
export const GET_ENDORSED_APPLICANTS_SUCCESS = 'GET_ENDORSED_APPLICANTS_SUCCESS'
export const GET_ENDORSED_APPLICANTS_FAIL = 'GET_ENDORSED_APPLICANTS_FAIL'

export const GET_SHORTLISTED_APPLICANTS = 'GET_SHORTLISTED_APPLICANTS'
export const GET_SHORTLISTED_APPLICANTS_SUCCESS =
  'GET_SHORTLISTED_APPLICANTS_SUCCESS'
export const GET_SHORTLISTED_APPLICANTS_FAIL = 'GET_SHORTLISTED_APPLICANTS_FAIL'

export const UPDATE_QUALIFIED_APPLICANT_EXAM_SCORE =
  'UPDATE_QUALIFIED_APPLICANT_EXAM_SCORE'

export const UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES =
  'UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES'
export const UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES_SUCCESS =
  'UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES_SUCCESS'
export const UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES_FAIL =
  'UPDATE_QUALIFIED_APPLICANTS_EXAM_SCORES_FAIL'

export const GET_APPLICANT_PDS = 'GET_APPLICANT_PDS'
export const GET_APPLICANT_PDS_SUCCESS = 'GET_APPLICANT_PDS_SUCCESS'
export const GET_APPLICANT_PDS_FAIL = 'GET_APPLICANT_PDS_FAIL'

export const GET_APPLICANT_WES = 'GET_APPLICANT_WES'
export const GET_APPLICANT_WES_SUCCESS = 'GET_APPLICANT_WES_SUCCESS'
export const GET_APPLICANT_WES_FAIL = 'GET_APPLICANT_WES_FAIL'

export const UPDATE_APPLICANT_APPLICATION_STATUS =
  'UPDATE_APPLICANT_APPLICATION_STATUS'
export const UPDATE_APPLICANT_APPLICATION_STATUS_SUCCESS =
  'UPDATE_APPLICANT_APPLICATION_STATUS_SUCCESS'
export const UPDATE_APPLICANT_APPLICATION_STATUS_FAIL =
  'UPDATE_APPLICANT_APPLICATION_STATUS_FAIL'

export const POST_DBMCSC_DETAILS = 'POST_DBMCSC_DETAILS'
export const POST_DBMCSC_DETAILS_SUCCESS = 'POST_DBMCSC_DETAILS_SUCCESS'
export const POST_DBMCSC_DETAILS_FAIL = 'POST_DBMCSC_DETAILS_FAIL'

export const GET_APPLICANT_DBMCSC_DETAILS = 'GET_APPLICANT_DBMCSC_DETAILS'
export const GET_APPLICANT_DBMCSC_DETAILS_SUCCESS =
  'GET_APPLICANT_DBMCSC_DETAILS_SUCCESS'
export const GET_APPLICANT_DBMCSC_DETAILS_FAIL =
  'GET_APPLICANT_DBMCSC_DETAILS_FAIL'

// action types for pulling data based on the form submitted (dbm-csc and form 33-b)
export const GET_DBMCSC_FORM33B_DETAILS = 'GET_DBMCSC_FORM33B_DETAILS'
export const GET_DBMCSC_FORM33B_DETAILS_SUCCESS = 'GET_DBMCSC_DETAILS_SUCCESS'
export const GET_DBMCSC_FORM33B_DETAILS_FAIL = 'GET_DBMCSC_DETAILS_FAIL'

export const PATCH_DBMCSC_DETAILS = 'PATCH_DBMCSC_DETAILS'
export const PATCH_DBMCSC_DETAILS_SUCCESS = 'PATCH_DBMCSC_DETAILS_SUCCESS'
export const PATCH_DBMCSC_DETAILS_FAIL = 'PATCH_DBMCSC_DETAILS_FAIL'

export const GET_DOCUMENT_RESULTS_OF_HIRING = 'GET_DOCUMENT_RESULTS_OF_HIRING'
export const GET_DOCUMENT_RESULTS_OF_HIRING_SUCCESS =
  'GET_DOCUMENT_RESULTS_OF_HIRING_SUCCESS'
export const GET_DOCUMENT_RESULTS_OF_HIRING_FAIL =
  'GET_DOCUMENT_RESULTS_OF_HIRING_FAIL'

export const GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED =
  'GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED'
export const GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED_SUCCESS =
  'GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED_SUCCESS'
export const GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED_FAIL =
  'GET_DOCUMENT_REPORT_ON_APPOINTMENTS_ISSUED_FAIL'

export const GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY =
  'GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY'
export const GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY_SUCCESS =
  'GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY_SUCCESS'
export const GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY_FAIL =
  'GET_DOCUMENT_CERTIFICATION_OF_ASSUMPTION_TO_DUTY_FAIL'

export const GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT =
  'GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT'
export const GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT_SUCCESS =
  'GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT_SUCCESS'
export const GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT_FAIL =
  'GET_DOCUMENT_CERTIFICATE_OF_APPOINTMENT_FAIL'

export const GET_HIRED_EXTERNAL_APPLICANTS = 'GET_HIRED_EXTERNAL_APPLICANTS'
export const GET_HIRED_EXTERNAL_APPLICANTS_SUCCESS =
  'GET_HIRED_EXTERNAL_APPLICANTS_SUCCESS'
export const GET_HIRED_EXTERNAL_APPLICANTS_FAIL =
  'GET_HIRED_EXTERNAL_APPLICANTS_FAIL'

export const RESET_APPLICANTS_RESPONSES = 'RESET_APPLICANTS_RESPONSES'
