// GET requests
export const GET_SERVICE_RECORDS = 'GET_SERVICE_RECORDS'
export const GET_SERVICE_RECORDS_SUCCESS = 'GET_SERVICE_RECORDS_SUCCESS'
export const GET_SERVICE_RECORDS_FAIL = 'GET_SERVICE_RECORDS_FAIL'

export const RESET_SERVICE_RECORD_ERROR_LOG = 'RESET_SERVICE_RECORD_ERROR_LOG'

// POST, PATCH, PUT & DELETE request
export const POST_EMPLOYEE_SEPARATION = 'POST_EMPLOYEE_SEPARATION'
export const POST_EMPLOYEE_SEPARATION_SUCCESS =
  'POST_EMPLOYEE_SEPARATION_SUCCESS'
export const POST_EMPLOYEE_SEPARATION_FAIL = 'POST_EMPLOYEE_SEPARATION_FAIL'
