// GET requests
export const GET_EMPLOYEE_TRAININGS = 'GET_EMPLOYEE_TRAININGS'
export const GET_EMPLOYEE_TRAININGS_SUCCESS = 'GET_EMPLOYEE_TRAININGS_SUCCESS'
export const GET_EMPLOYEE_TRAININGS_FAIL = 'GET_EMPLOYEE_TRAININGS_FAIL'
