export const SUBMIT_EMPLOYEE_ASSIGN = 'SUBMIT_EMPLOYEE_ASSIGN'
export const SUBMIT_EMPLOYEE_ASSIGN_SUCCESS = 'SUBMIT_EMPLOYEE_ASSIGN_SUCCESS'
export const SUBMIT_EMPLOYEE_ASSIGN_FAILED = 'SUBMIT_EMPLOYEE_ASSIGN_FAILED'
export const RESET_EMPLOYEE_ASSIGN = 'RESET_EMPLOYEE_ASSIGN'

export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST'
export const GET_EMPLOYEE_LIST_SUCCESS = 'GET_EMPLOYEE_LIST_SUCCESS'
export const GET_EMPLOYEE_LIST_FAILED = 'GET_EMPLOYEE_LIST_FAILED'

export const GET_EMPLOYEE_PDS = 'GET_EMPLOYEE_PDS'
export const GET_EMPLOYEE_PDS_SUCCESS = 'GET_EMPLOYEE_PDS_SUCCESS'
export const GET_EMPLOYEE_PDS_FAILED = 'GET_EMPLOYEE_PDS_FAILED'

export const GET_EMPLOYEE_201 = 'GET_EMPLOYEE_201'
export const GET_EMPLOYEE_201_SUCCESS = 'GET_EMPLOYEE_201_SUCCESS'
export const GET_EMPLOYEE_201_FAILED = 'GET_EMPLOYEE_201_FAILED'

export const GET_EMPLOYEE_DETAILS_REPORT = 'GET_EMPLOYEE_DETAILS_REPORT'
export const GET_EMPLOYEE_DETAILS_REPORT_SUCCESS =
  'GET_EMPLOYEE_DETAILS_REPORT_SUCCESS'
export const GET_EMPLOYEE_DETAILS_REPORT_FAIL =
  'GET_EMPLOYEE_DETAILS_REPORT_FAIL'

export const GET_EMPLOYEE_BASIC_INFO = 'GET_EMPLOYEE_BASIC_INFO'
export const GET_EMPLOYEE_BASIC_INFO_SUCCESS = 'GET_EMPLOYEE_BASIC_INFO_SUCCESS'
export const GET_EMPLOYEE_BASIC_INFO_FAIL = 'GET_EMPLOYEE_BASIC_INFO_FAIL'

export const RESET_EMPLOYEE_ERROR_LOG = 'RESET_EMPLOYEE_ERROR_LOG'

export const UPDATE_EMPLOYEE_BASIC_INFO = 'UPDATE_EMPLOYEE_BASIC_INFO'
export const UPDATE_EMPLOYEE_BASIC_INFO_SUCCESS =
  'UPDATE_EMPLOYEE_BASIC_INFO_SUCCESS'
export const UPDATE_EMPLOYEE_BASIC_INFO_FAIL = 'UPDATE_EMPLOYEE_BASIC_INFO_FAIL'

export const RESET_RESPONSE_ON_UPDATE_BASIC_INFO =
  'RESET_RESPONSE_ON_UPDATE_BASIC_INFO'
