// POST, PUT, PATCH, DELETE requests
export const REGISTER_PERMANENT_EMPLOYEE = 'REGISTER_PERMANENT_EMPLOYEE'
export const REGISTER_PERMANENT_EMPLOYEE_SUCCESS =
  'REGISTER_PERMANENT_EMPLOYEE_SUCCESS'
export const REGISTER_PERMANENT_EMPLOYEE_FAILED =
  'REGISTER_PERMANENT_EMPLOYEE_FAILED'

export const REGISTER_CAS_JO_COS_EMPLOYEE = 'REGISTER_CAS_JO_COS_EMPLOYEE'
export const REGISTER_CAS_JO_COS_EMPLOYEE_SUCCESS =
  'REGISTER_CAS_JO_COS_EMPLOYEE_SUCCESS'
export const REGISTER_CAS_JO_COS_EMPLOYEE_FAILED =
  'REGISTER_CAS_JO_COS_EMPLOYEE_FAILED'

export const REGISTER_CASUAL_EMPLOYEE = 'REGISTER_CASUAL_EMPLOYEE'
export const REGISTER_CASUAL_EMPLOYEE_SUCCESS =
  'REGISTER_CASUAL_EMPLOYEE_SUCCESS'
export const REGISTER_CASUAL_EMPLOYEE_FAILED = 'REGISTER_CASUAL_EMPLOYEE_FAILED'

export const REGISTER_JO_EMPLOYEE = 'REGISTER_JO_EMPLOYEE'
export const REGISTER_JO_EMPLOYEE_SUCCESS = 'REGISTER_JO_EMPLOYEE_SUCCESS'
export const REGISTER_JO_EMPLOYEE_FAILED = 'REGISTER_JO_EMPLOYEE_FAILED'

export const REGISTER_COS_EMPLOYEE = 'REGISTER_COS_EMPLOYEE'
export const REGISTER_COS_EMPLOYEE_SUCCESS = 'REGISTER_COS_EMPLOYEE_SUCCESS'
export const REGISTER_COS_EMPLOYEE_FAILED = 'REGISTER_COS_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE_BASIC_INFO = 'UPDATE_EMPLOYEE_BASIC_INFO'
export const UPDATE_EMPLOYEE_BASIC_INFO_SUCCESS =
  'UPDATE_EMPLOYEE_BASIC_INFO_SUCCESS'
export const UPDATE_EMPLOYEE_BASIC_INFO_FAIL = 'UPDATE_EMPLOYEE_BASIC_INFO_FAIL'

export const RESET_EMPLOYEE_RESPONSE_AND_ERROR =
  'RESET_EMPLOYEE_RESPONSE_AND_ERROR'

// GET requests
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST'
export const GET_EMPLOYEE_LIST_SUCCESS = 'GET_EMPLOYEE_LIST_SUCCESS'
export const GET_EMPLOYEE_LIST_FAILED = 'GET_EMPLOYEE_LIST_FAILED'

export const GET_EMPLOYEE_PDS = 'GET_EMPLOYEE_PDS'
export const GET_EMPLOYEE_PDS_SUCCESS = 'GET_EMPLOYEE_PDS_SUCCESS'
export const GET_EMPLOYEE_PDS_FAILED = 'GET_EMPLOYEE_PDS_FAILED'

// export const GET_EMPLOYEE_201 = 'GET_EMPLOYEE_201'
// export const GET_EMPLOYEE_201_SUCCESS = 'GET_EMPLOYEE_201_SUCCESS'
// export const GET_EMPLOYEE_201_FAILED = 'GET_EMPLOYEE_201_FAILED'

export const GET_EMPLOYEE_DETAILS_REPORT = 'GET_EMPLOYEE_DETAILS_REPORT'
export const GET_EMPLOYEE_DETAILS_REPORT_SUCCESS =
  'GET_EMPLOYEE_DETAILS_REPORT_SUCCESS'
export const GET_EMPLOYEE_DETAILS_REPORT_FAIL =
  'GET_EMPLOYEE_DETAILS_REPORT_FAIL'

export const GET_EMPLOYEE_BASIC_INFO = 'GET_EMPLOYEE_BASIC_INFO'
export const GET_EMPLOYEE_BASIC_INFO_SUCCESS = 'GET_EMPLOYEE_BASIC_INFO_SUCCESS'
export const GET_EMPLOYEE_BASIC_INFO_FAIL = 'GET_EMPLOYEE_BASIC_INFO_FAIL'

export const GET_EMPLOYEE_HEADER_INFO = 'GET_EMPLOYEE_HEADER_INFO'
export const GET_EMPLOYEE_HEADER_INFO_SUCCESS =
  'GET_EMPLOYEE_HEADER_INFO_SUCCESS'
export const GET_EMPLOYEE_HEADER_INFO_FAIL = 'GET_EMPLOYEE_HEADER_INFO_FAIL'

export const RESET_EMPLOYEE_ERROR_LOG = 'RESET_EMPLOYEE_ERROR_LOG'
