/* OFFICES */
export const GET_OFFICES = "GET_OFFICES"
export const GET_OFFICES_SUCCESS = "GET_OFFICES_SUCCESS"

export const POST_OFFICE = "POST_OFFICE"
export const POST_OFFICE_SUCCESS = "POST_OFFICE_SUCCESS"

export const PUT_OFFICE = "PUT_OFFICE"
export const PUT_OFFICE_SUCCESS = "PUT_OFFICE_SUCCESS"

export const DELETE_OFFICE = "DELETE_OFFICE"
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS"

export const RESET_OFFICE = "RESET_OFFICE"
export const OFFICE_API_ERROR = "OFFICE_API_ERROR"
