export const GET_ALL_OIC = "GET_ALL_OIC"
export const GET_ALL_OIC_SUCCESS = "GET_ALL_OIC_SUCCESS"
export const GET_ALL_OIC_FAIL = "GET_ALL_OIC_FAIL"

export const GET_SG20_UP_EMPLOYEES = "GET_SG20_UP_EMPLOYEES"
export const GET_SG20_UP_EMPLOYEES_SUCCESS = "GET_SG20_UP_EMPLOYEES_SUCCESS"
export const GET_SG20_UP_EMPLOYEES_FAIL = "GET_SG20_UP_EMPLOYEES_FAIL"

export const GET_VACANT_MANAGERIAL_POSITIONS = "GET_VACANT_MANAGERIAL_POSITIONS"
export const GET_VACANT_MANAGERIAL_POSITIONS_SUCCESS =
  "GET_VACANT_MANAGERIAL_POSITIONS_SUCCESS"
export const GET_VACANT_MANAGERIAL_POSITIONS_FAIL =
  "GET_VACANT_MANAGERIAL_POSITIONS_FAIL"

export const POST_ASSIGN_OIC = "POST_ASSIGN_OIC"
export const POST_ASSIGN_OIC_SUCCESS = "POST_ASSIGN_OIC_SUCCESS"
export const POST_ASSIGN_OIC_FAIL = "POST_ASSIGN_OIC_FAIL"

export const DELETE_UNASSIGN_OIC = "DELETE_UNASSIGN_OIC"
export const DELETE_UNASSIGN_OIC_SUCCESS = "DELETE_UNASSIGN_OIC_SUCCESS"
export const DELETE_UNASSIGN_OIC_FAIL = "DELETE_UNASSIGN_OIC_FAIL"

export const RESET_OIC_RESPONSE = "RESET_OIC_RESPONSE"
