export const GET_JOB_DESCRIPTION = "GET_JOB_DESCRIPTION"
export const GET_JOB_DESCRIPTION_SUCCESS = "GET_JOB_DESCRIPTION_SUCCESS"

export const UPDATE_JOB_DESCRIPTION = "UPDATE_JOB_DESCRIPTION"
export const UPDATE_JOB_DESCRIPTION_SUCCESS = "UPDATE_JOB_DESCRIPTION_SUCCESS"

export const JOB_DESCRIPTION_API_FAIL = "JOB_DESCRIPTION_API_FAIL"
