export const GET_SALARY_GRADE_LIST = "GET_SALARY_GRADE_LIST"
export const GET_SALARY_GRADE_LIST_SUCCESS = "GET_SALARY_GRADE_LIST_SUCCESS"

export const PUT_SALARY_GRADE_LIST = "PUT_SALARY_GRADE_LIST"
export const PUT_SALARY_GRADE_LIST_SUCCESS = "PUT_SALARY_GRADE_LIST_SUCCESS"

export const SALARY_GRADE_API_FAIL = "SALARY_GRADE_API_FAIL"

export const GET_SALARY_GRADE_LIST_STEP_INCREMENT =
  "GET_SALARY_GRADE_LIST_STEP_INCREMENT"
export const GET_SALARY_GRADE_LIST_STEP_INCREMENT_SUCCESS =
  "GET_SALARY_GRADE_STEP_INCREMENT_SUCCESS"
export const GET_SALARY_GRADE_LIST_STEP_INCREMENT_FAIL =
  "GET_SALARY_GRADE_STEP_INCREMENT_FAIL"

export const GET_SALARY_GRADE_LIST_STEP_INCREMENT_ONE =
  "GET_SALARY_GRADE_LIST_STEP_INCREMENT_ONE"
export const GET_SALARY_GRADE_LIST_STEP_INCREMENT_ONE_SUCCESS =
  "GET_SALARY_GRADE_STEP_INCREMENT_ONE_SUCCESS"
export const GET_SALARY_GRADE_LIST_STEP_INCREMENT_ONE_FAIL =
  "GET_SALARY_GRADE_STEP_INCREMENT_ONE_FAIL"

export const RESET_SALARY_GRADE_RESPONSES = "RESET_SALARY_GRADE_RESPONSES"
