/** Get Dashboard Chart data */
// export const API_SUCCESS = 'API_SUCCESS'
// export const API_FAIL = 'API_FAIL'
// export const GET_CHARTS_DATA = 'GET_CHARTS_DATA'

// Get employees count
export const GET_EMPLOYEES_COUNT = 'GET_EMPLOYEES_COUNT'
export const GET_EMPLOYEES_COUNT_SUCCESS = 'GET_EMPLOYEES_COUNT_SUCCESS'
export const GET_EMPLOYEES_COUNT_FAIL = 'GET_EMPLOYEES_COUNT_FAIL'

// Get applicants count
export const GET_APPLICANTS_COUNT = 'GET_APPLICANTS_COUNT'
export const GET_APPLICANTS_COUNT_SUCCESS = 'GET_APPLICANTS_COUNT_SUCCESS'
export const GET_APPLICANTS_COUNT_FAIL = 'GET_APPLICANTS_COUNT_FAIL'

// Get approved PRFs count
export const GET_APPROVED_PRF_COUNT = 'GET_APPROVED_PRF_COUNT'
export const GET_APPROVED_PRF_COUNT_SUCCESS = 'GET_APPROVED_PRF_COUNT_SUCCESS'
export const GET_APPROVED_PRF_COUNT_FAIL = 'GET_APPROVED_PRF_COUNT_FAIL'

// Get birthday celebrants for the month
export const GET_BIRTHDAY_CELEBRANTS = 'GET_BIRTHDAY_CELEBRANTS'
export const GET_BIRTHDAY_CELEBRANTS_SUCCESS = 'GET_BIRTHDAY_CELEBRANTS_SUCCESS'
export const GET_BIRTHDAY_CELEBRANTS_FAIL = 'GET_BIRTHDAY_CELEBRANTS_FAIL'

// Get nature of appointment distribution
export const GET_NOA_DISTRIBUTION = 'GET_NOA_DISTRIBUTION'
export const GET_NOA_DISTRIBUTION_SUCCESS = 'GET_NOA_DISTRIBUTION_SUCCESS'
export const GET_NOA_DISTRIBUTION_FAIL = 'GET_NOA_DISTRIBUTION_FAIL'

// Get personnel distribution
export const GET_PERSONNEL_DISTRIBUTION = 'GET_PERSONNEL_DISTRIBUTION'
export const GET_PERSONNEL_DISTRIBUTION_SUCCESS =
  'GET_PERSONNEL_DISTRIBUTION_SUCCESS'
export const GET_PERSONNEL_DISTRIBUTION_FAIL = 'GET_PERSONNEL_DISTRIBUTION_FAIL'

// Get age bracket distribution
export const GET_AGE_DISTRIBUTION = 'GET_AGE_DISTRIBUTION'
export const GET_AGE_DISTRIBUTION_SUCCESS = 'GET_AGE_DISTRIBUTION_SUCCESS'
export const GET_AGE_DISTRIBUTION_FAIL = 'GET_AGE_DISTRIBUTION_FAIL'
