/** Get Dashboard Chart data */
export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";
export const GET_CHARTS_DATA = "GET_CHARTS_DATA";

// Get employees count
export const GET_EMPLOYEES_COUNT = "GET_EMPLOYEES_COUNT"
export const GET_EMPLOYEES_COUNT_SUCCESS = "GET_EMPLOYEES_COUNT_SUCCESS"
export const GET_EMPLOYEES_COUNT_FAIL = "GET_EMPLOYEES_COUNT_FAIL"

// Get applicants count
export const GET_APPLICANTS_COUNT = "GET_APPLICANTS_COUNT"
export const GET_APPLICANTS_COUNT_SUCCESS = "GET_APPLICANTS_COUNT_SUCCESS"
export const GET_APPLICANTS_COUNT_FAIL = "GET_APPLICANTS_COUNT_FAIL"

// Get approved PRFs count
export const GET_APPROVED_PRF_COUNT = "GET_APPROVED_PRF_COUNT"
export const GET_APPROVED_PRF_COUNT_SUCCESS = "GET_APPROVED_PRF_COUNT_SUCCESS"
export const GET_APPROVED_PRF_COUNT_FAIL = "GET_APPROVED_PRF_COUNT_FAIL"