/* DIVISION */
export const GET_DIVISIONS = "GET_DIVISIONS"
export const GET_DIVISIONS_SUCCESS = "GET_DIVISIONS_SUCCESS"

export const POST_DIVISION = "POST_DIVISION"
export const POST_DIVISION_SUCCESS = "POST_DIVISION_SUCCESS"

export const PUT_DIVISION = "PUT_DIVISION"
export const PUT_DIVISION_SUCCESS = "PUT_DIVISION_SUCCESS"

export const DELETE_DIVISION = "DELETE_DIVISION"
export const DELETE_DIVISION_SUCCESS = "DELETE_DIVISION_SUCCESS"

export const RESET_DIVISION = "RESET_DIVISION"
export const DIVISION_API_ERROR = "DIVISION_API_ERROR"

