export const GET_PLANTILLA = "GET_PLANTILLA"
export const GET_PLANTILLA_SUCCESS = "GET_PLANTILLA_SUCCESS"

export const GET_PLANTILLA_POSITION = "GET_PLANTILLA_POSITION"
export const GET_PLANTILLA_POSITION_SUCCESS = "GET_PLANTILLA_POSITION_SUCCESS"
export const RESET_PLANTILLA_POSITION = "RESET_PLANTILLA_POSITION"

export const GET_PLANTILLA_POSITIONS = "GET_PLANTILLA_POSITIONS"
export const GET_PLANTILLA_POSITIONS_SUCCESS = "GET_PLANTILLA_POSITIONS_SUCCESS"
export const RESET_PLANTILLA_POSITIONS = "RESET_PLANTILLA_POSITIONS"

export const SUBMIT_POSITION = "SUBMIT_POSITION"
export const SUBMIT_POSITION_SUCCESS = "SUBMIT_POSITION_SUCCESS"

export const GET_EMPLOYEE_DETAILS_BY_PLANTILLA =
  'GET_EMPLOYEE_DETAILS_BY_PLANTILLA'
export const GET_EMPLOYEE_DETAILS_BY_PLANTILLA_SUCCESS =
  'GET_EMPLOYEE_DETAILS_BY_PLANTILLA_SUCCESS'
export const GET_EMPLOYEE_DETAILS_BY_PLANTILLA_FAIL =
  'GET_EMPLOYEE_DETAILS_BY_PLANTILLA_FAIL'

export const PLANTILLA_API_ERROR = "PLANTILLA_API_ERROR"
