// Proficiency Levels
export const GET_COMPETENCY_PROFICIENCY_LEVELS =
  'GET_COMPETENCY_PROFICIENCY_LEVELS'
export const GET_COMPETENCY_PROFICIENCY_LEVELS_SUCCESS =
  'GET_COMPETENCY_PROFICIENCY_LEVELS_SUCCESS'
export const GET_COMPETENCY_PROFICIENCY_LEVELS_FAIL =
  'GET_COMPETENCY_PROFICIENCY_LEVELS_FAIL'

export const UPDATE_COMPETENCY_PROFICIENCY_LEVEL =
  'UPDATE_COMPETENCY_PROFICIENCY_LEVEL'

export const UPDATE_POSITION_PROFICIENCY_LEVELS =
  'UPDATE_POSITION_PROFICIENCY_LEVELS'
export const UPDATE_POSITION_PROFICIENCY_LEVELS_SUCCESS =
  'UPDATE_POSITION_PROFICIENCY_LEVELS_SUCCESS'
export const UPDATE_POSITION_PROFICIENCY_LEVELS_FAIL =
  'UPDATE_POSITION_PROFICIENCY_LEVELS_FAIL'

// Functional and Cross-cutting Competencies
export const GET_POSITION_FUNCTIONAL_COMPETENCIES =
  'GET_POSITION_FUNCTIONAL_COMPETENCIES'
export const GET_POSITION_FUNCTIONAL_COMPETENCIES_SUCCESS =
  'GET_POSITION_FUNCTIONAL_COMPETENCIES_SUCCESS'
export const GET_POSITION_FUNCTIONAL_COMPETENCIES_FAIL =
  'GET_POSITION_FUNCTIONAL_COMPETENCIES_FAIL'

// Managerial Competencies
export const GET_POSITION_MANAGERIAL_COMPETENCIES =
  'GET_POSITION_MANAGERIAL_COMPETENCIES'
export const GET_POSITION_MANAGERIAL_COMPETENCIES_SUCCESS =
  'GET_POSITION_MANAGERIAL_COMPETENCIES_SUCCESS'
export const GET_POSITION_MANAGERIAL_COMPETENCIES_FAIL =
  'GET_POSITION_MANAGERIAL_COMPETENCIES_FAIL'

export const GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES =
  'GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES'
export const GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES_SUCCESS =
  'GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES_SUCCESS'
export const GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES_FAIL =
  'GET_POSITION_AVAILABLE_FUNCTIONAL_COMPETENCIES_FAIL'

export const ASSIGN_COMPETENCIES_OF_POSITION = 'ASSIGN_COMPETENCIES_OF_POSITION'
export const ASSIGN_COMPETENCIES_OF_POSITION_SUCCESS =
  'ASSIGN_COMPETENCIES_OF_POSITION_SUCCESS'
export const ASSIGN_COMPETENCIES_OF_POSITION_FAIL =
  'ASSIGN_COMPETENCIES_OF_POSITION_FAIL'

export const UNASSIGN_COMPETENCIES_OF_POSITION =
  'UNASSIGN_COMPETENCIES_OF_POSITION'
export const UNASSIGN_COMPETENCIES_OF_POSITION_SUCCESS =
  'UNASSIGN_COMPETENCIES_OF_POSITION_SUCCESS'
export const UNASSIGN_COMPETENCIES_OF_POSITION_FAIL =
  'UNASSIGN_COMPETENCIES_OF_POSITION_FAIL'

export const RESET_POSITION_COMPETENCIES = 'RESET_POSITION_COMPETENCIES'

export const SELECT_POSITION_FUNCTIONAL_COMPETENCY_ROW =
  'SELECT_POSITION_FUNCTIONAL_COMPETENCY_ROW'
export const UNSELECT_POSITION_FUNCTIONAL_COMPETENCY_ROW =
  'UNSELECT_POSITION_FUNCTIONAL_COMPETENCY_ROW'
export const RESET_POSITION_SELECTED_FUNCTIONAL_COMPETENCY_ROWS =
  'RESET_POSITION_SELECTED_FUNCTIONAL_COMPETENCY_ROWS'
