export const GET_OCCUPATIONS = "GET_OCCUPATIONS"
export const GET_OCCUPATIONS_SUCCESS = "GET_OCCUPATIONS_SUCCESS"
export const GET_OCCUPATIONS_FAIL = "GET_OCCUPATIONS_FAIL"

export const GET_OCCUPATION = "GET_OCCUPATION"
export const GET_OCCUPATION_SUCCESS = "GET_OCCUPATION_SUCCESS"
export const GET_OCCUPATION_FAIL = "GET_OCCUPATION_FAIL"

export const POST_OCCUPATION = "POST_OCCUPATION"
export const POST_OCCUPATION_SUCCESS = "POST_OCCUPATION_SUCCESS"
export const POST_OCCUPATION_FAIL = "POST_OCCUPATION_FAIL"

export const PUT_OCCUPATION = "PUT_OCCUPATION"
export const PUT_OCCUPATION_SUCCESS = "PUT_OCCUPATION_SUCCESS"
export const PUT_OCCUPATION_FAIL = "PUT_OCCUPATION_FAIL"

export const DELETE_OCCUPATION = "DELETE_OCCUPATION"
export const DELETE_OCCUPATION_SUCCESS = "DELETE_OCCUPATION_SUCCESS"
export const DELETE_OCCUPATION_FAIL = "DELETE_OCCUPATION_FAIL"

export const GET_OCCUPATIONAL_GROUP_POSITIONS =
  "GET_OCCUPATIONAL_GROUP_POSITIONS"
export const GET_OCCUPATIONAL_GROUP_POSITIONS_SUCCESS =
  "GET_OCCUPATIONAL_GROUP_POSITIONS_SUCCESS"
export const GET_OCCUPATIONAL_GROUP_POSITIONS_FAIL =
  "GET_OCCUPATIONAL_GROUP_POSITIONS_FAIL"

export const GET_POSITIONS_WITHOUT_OCCUPATION =
  "GET_POSITIONS_WITHOUT_OCCUPATION"
export const GET_POSITIONS_WITHOUT_OCCUPATION_SUCCESS =
  "GET_POSITIONS_WITHOUT_OCCUPATION_SUCCESS"
export const GET_POSITIONS_WITHOUT_OCCUPATION_FAIL =
  "GET_POSITIONS_WITHOUT_OCCUPATION_FAIL"

export const ASSIGN_POSITIONS_TO_OCCUPATION = "ASSIGN_POSITIONS_TO_OCCUPATION"
export const ASSIGN_POSITIONS_TO_OCCUPATION_SUCCESS =
  "ASSIGN_COMMITTEE_MEMBERS_SUCCESS"
export const ASSIGN_POSITIONS_TO_OCCUPATION_FAIL =
  "ASSIGN_COMMITTEE_MEMBERS_FAIL"

export const UNASSIGN_POSITIONS_TO_OCCUPATION =
  "UNASSIGN_POSITIONS_TO_OCCUPATION"
export const UNASSIGN_POSITIONS_TO_OCCUPATION_SUCCESS =
  "UNASSIGN_COMMITTEE_MEMBERS_SUCCESS"
export const UNASSIGN_POSITIONS_TO_OCCUPATION_FAIL =
  "UNASSIGN_COMMITTEE_MEMBERS_FAIL"

export const RESET_OCCUPATION_RESPONSES = "RESET_OCCUPATION_RESPONSES"

export const SELECT_POSITION_ROW = "SELECT_POSITION_ROW"
export const UNSELECT_POSITION_ROW = "UNSELECT_POSITION_ROW"
export const RESET_SELECTED_POSITION_ROWS = "RESET_SELECTED_POSITION_ROWS"
