// PRF List
export const GET_PRFLIST = 'GET_PRFLIST'
export const GET_PRFLIST_SUCCESS = 'GET_PRFLIST_SUCCESS'
export const GET_PRFLIST_FAIL = 'GET_PRFLIST_FAIL'

// Approved PRF List
// export const GET_APPROVED_PRFLIST = 'GET_APPROVED_PRFLIST'
// export const GET_APPROVED_PRFLIST_SUCCESS = 'GET_APPROVED_PRFLIST_SUCCESS'
// export const GET_APPROVED_PRFLIST_FAIL = 'GET_APPROVED_PRFLIST_FAIL'

// Publication Positions
export const GET_APPROVED_PUBLICATION_POSITIONS =
  'GET_APPROVED_PUBLICATION_POSITIONS'
export const GET_APPROVED_PUBLICATION_POSITIONS_SUCCESS =
  'GET_APPROVED_PUBLICATION_POSITIONS_SUCCESS'
export const GET_APPROVED_PUBLICATION_POSITIONS_FAIL =
  'GET_APPROVED_PUBLICATION_POSITIONS_FAIL'

// Submit
export const SUBMIT_PRF = 'SUBMIT_PRF'
export const SUBMIT_PRF_SUCCESS = 'SUBMIT_PRF_SUCCESS'
export const SUBMIT_PRF_FAILED = 'SUBMIT_PRF_FAILED'

// Single PRF
export const GET_SINGLE_PRF = 'GET_SINGLE_PRF'
export const GET_SINGLE_PRF_SUCCESS = 'GET_SINGLE_PRF_SUCCESS'
export const GET_SINGLE_PRF_FAIL = 'GET_SINGLE_PRF_FAIL'

// PRF Trail
export const GET_PRF_TRAIL = 'GET_PRF_TRAIL'
export const GET_PRF_TRAIL_SUCCESS = 'GET_PRF_TRAIL_SUCCESS'
export const GET_PRF_TRAIL_FAIL = 'GET_PRF_TRAIL_FAIL'
