export const GET_HRMS_MODULES = "GET_HRMS_MODULES"
export const GET_HRMS_MODULES_SUCCESS = "GET_HRMS_MODULES_SUCCESS"

export const POST_HRMS_MODULE = "POST_HRMS_MODULE"
export const POST_HRMS_MODULE_SUCCESS = "POST_HRMS_MODULE_SUCCESS"

export const DELETE_HRMS_MODULE = "DELETE_HRMS_MODULE"
export const DELETE_HRMS_MODULE_SUCCESS = "DELETE_HRMS_MODULE_SUCCESS"

export const PATCH_HRMS_MODULE = "PATCH_HRMS_MODULE"
export const PATCH_HRMS_MODULE_SUCCESS = "PATCH_HRMS_MODULE_SUCCESS"

export const HRMS_MODULE_API_FAIL = "HRMS_MODULE_API_FAIL"
export const RESET_HRMS_MODULE_RESPONSE = "RESET_HRMS_MODULE_RESPONSE"
