export const GET_PUBLICATIONS = "GET_PUBLICATIONS"
export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS"
export const GET_PUBLICATIONS_FAIL = "GET_PUBLICATIONS_FAIL"

export const RESET_PUBLICATIONS = "RESET_PUBLICATIONS"

export const GET_CALENDAR_INTERVIEW_SCHEDULES =
  "GET_CALENDAR_INTERVIEW_SCHEDULE"
export const GET_CALENDAR_INTERVIEW_SCHEDULES_SUCCESS =
  "GET_CALENDAR_INTERVIEW_SCHEDULE_SUCCESS"
export const GET_CALENDAR_INTERVIEW_SCHEDULES_FAIL =
  "GET_CALENDAR_INTERVIEW_SCHEDULE_FAIL"

export const GET_PUBLICATION_DOCUMENT_DETAILS =
  "GET_PUBLICATION_DOCUMENT_DETAILS"
export const GET_PUBLICATION_DOCUMENT_DETAILS_SUCCESS =
  "GET_PUBLICATION_DOCUMENT_DETAILS_SUCCESS"
export const GET_PUBLICATION_DOCUMENT_DETAILS_FAIL =
  "GET_PUBLICATION_DOCUMENT_DETAILS_FAIL"

export const PUT_PUBLICATION_STATUS = "PUT_PUBLICATION_STATUS"
export const PUT_PUBLICATION_STATUS_SUCCESS = "PUT_PUBLICATION_STATUS_SUCCESS"
export const PUT_PUBLICATION_STATUS_FAIL = "PUT_PUBLICATION_STATUS_FAIL"

export const POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY =
  "POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY"
export const POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY_SUCCESS =
  "POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY_SUCCESS"
export const POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY_FAIL =
  "POST_ENDORSEMENT_OF_QUALIFIED_APPLICANTS_TO_REQUESTING_ENTITY_FAIL"

export const GET_PUBLICATION_SCHEDULES = "GET_PUBLICATION_SCHEDULES"
export const GET_PUBLICATION_SCHEDULES_SUCCESS =
  "GET_PUBLICATION_SCHEDULES_SUCCESS"
export const GET_PUBLICATION_SCHEDULES_FAIL = "GET_PUBLICATION_SCHEDULES_FAIL"

export const POST_SCHEDULE_EXAM_INTERVIEW = "POST_SCHEDULE_EXAM_INTERVIEW"
export const POST_SCHEDULE_EXAM_INTERVIEW_SUCCESS =
  "POST_SCHEDULE_EXAM_INTERVIEW_SUCCESS"
export const POST_SCHEDULE_EXAM_INTERVIEW_FAIL =
  "POST_SCHEDULE_EXAM_INTERVIEW_FAIL"

export const PATCH_SCHEDULE_EXAM_INTERVIEW = "PATCH_SCHEDULE_EXAM_INTERVIEW"
export const PATCH_SCHEDULE_EXAM_INTERVIEW_SUCCESS =
  "PATCH_SCHEDULE_EXAM_INTERVIEW_SUCCESS"
export const PATCH_SCHEDULE_EXAM_INTERVIEW_FAIL =
  "PATCH_SCHEDULE_EXAM_INTERVIEW_FAIL"

export const PATCH_SET_APPOINTMENT_EFFECTIVITY =
  "PATCH_SET_APPOINTMENT_EFFECTIVITY"
export const PATCH_SET_APPOINTMENT_EFFECTIVITY_SUCCESS =
  "PATCH_SET_APPOINTMENT_EFFECTIVITY_SUCCESS"
export const PATCH_SET_APPOINTMENT_EFFECTIVITY_FAIL =
  "PATCH_SET_APPOINTMENT_EFFECTIVITY_FAIL"

export const GET_PUBLICATIONS_WITH_HIRED_APPLICANTS =
  "GET_PUBLICATIONS_WITH_HIRED_APPLICANTS"
export const GET_PUBLICATIONS_WITH_HIRED_APPLICANTS_SUCCESS =
  "GET_PUBLICATIONS_WITH_HIRED_APPLICANTS_SUCCESS"
export const GET_PUBLICATIONS_WITH_HIRED_APPLICANTS_FAIL =
  "GET_PUBLICATIONS_WITH_HIRED_APPLICANTS_FAIL"

export const GET_AVAILABLE_ITEM_NUMBERS = "GET_AVAILABLE_ITEM_NUMBERS"
export const GET_AVAILABLE_ITEM_NUMBERS_SUCCESS =
  "GET_AVAILABLE_ITEM_NUMBERS_SUCCESS"
export const GET_AVAILABLE_ITEM_NUMBERS_FAIL = "GET_AVAILABLE_ITEM_NUMBERS_FAIL"

export const RESET_PUBLICATION_RESPONSES = "RESET_PUBLICATION_RESPONSES"
