export const POST_COMMITTEE = "POST_COMMITTEE"
export const POST_COMMITTEE_SUCCESS = "POST_COMMITTEE_SUCCESS"

export const PUT_COMMITTEE = "PUT_COMMITTEE"
export const PUT_COMMITTEE_SUCCESS = "PUT_COMMITTEE_SUCCESS"

export const DELETE_COMMITTEE = "DELETE_COMMITTEE"
export const DELETE_COMMITTEE_SUCCESS = "DELETE_COMMITTEE_SUCCESS"

export const GET_COMMITTEES = "GET_COMMITTEES"
export const GET_COMMITTEES_SUCCESS = "GET_COMMITTEES_SUCCESS"

export const COMMITTEE_API_FAIL = "COMMITTEE_API_FAIL"

export const GET_COMMITTEE_MEMBERS = "GET_COMMITTEE_MEMBERS"
export const GET_COMMITTEE_MEMBERS_SUCCESS = "GET_COMMITTEE_MEMBERS_SUCCESS"
export const GET_COMMITTEE_MEMBERS_FAIL = "GET_COMMITTEE_MEMBERS_FAIL"

export const ASSIGN_COMMITTEE_MEMBERS = "ASSIGN_COMMITTEE_MEMBERS"
export const ASSIGN_COMMITTEE_MEMBERS_SUCCESS =
  "ASSIGN_COMMITTEE_MEMBERS_SUCCESS"
export const ASSIGN_COMMITTEE_MEMBERS_FAIL = "ASSIGN_COMMITTEE_MEMBERS_FAIL"

export const UNASSIGN_COMMITTEE_MEMBERS = "UNASSIGN_COMMITTEE_MEMBERS"
export const UNASSIGN_COMMITTEE_MEMBERS_SUCCESS =
  "UNASSIGN_COMMITTEE_MEMBERS_SUCCESS"
export const UNASSIGN_COMMITTEE_MEMBERS_FAIL = "UNASSIGN_COMMITTEE_MEMBERS_FAIL"

export const RESET_COMMITTEE_RESPONSES = "RESET_COMMITTEE_RESPONSES"

export const GET_UNASSIGNED_EMPLOYEES = "GET_UNASSIGNED_EMPLOYEES"
export const GET_UNASSIGNED_EMPLOYEES_SUCCESS =
  "GET_UNASSIGNED_EMPLOYEES_SUCCESS"
export const GET_UNASSIGNED_EMPLOYEES_FAIL = "GET_UNASSIGNED_EMPLOYEES_FAIL"

export const SELECT_EMPLOYEE_ROW = "SELECT_EMPLOYEE_ROW"
export const UNSELECT_EMPLOYEE_ROW = "UNSELECT_EMPLOYEE_ROW"
export const RESET_SELECTED_EMPLOYEE_ROWS = "RESET_SELECTED_EMPLOYEE_ROWS"