export const POST_DUTY = "POST_DUTY"
export const POST_DUTY_SUCCESS = "POST_DUTY_SUCCESS"

export const PUT_DUTY = "PUT_DUTY"
export const PUT_DUTY_SUCCESS = "PUT_DUTY_SUCCESS"

export const DELETE_DUTY = "DELETE_DUTY"
export const DELETE_DUTY_SUCCESS = "DELETE_DUTY_SUCCESS"

export const GET_DUTIES = "GET_DUTIES"
export const GET_DUTIES_SUCCESS = "GET_DUTIES_SUCCESS"

export const DUTY_API_FAIL = "DUTY_API_FAIL"

export const GET_OCCUPATION_DUTIES = "GET_OCCUPATION_DUTIES"
export const GET_OCCUPATION_DUTIES_SUCCESS = "GET_OCCUPATION_DUTIES_SUCCESS"
export const GET_OCCUPATION_DUTIES_FAIL = "GET_OCCUPATION_DUTIES_FAIL"

export const ASSIGN_OCCUPATION_DUTIES = "ASSIGN_OCCUPATION_DUTIES"
export const ASSIGN_OCCUPATION_DUTIES_SUCCESS =
  "ASSIGN_OCCUPATION_DUTIES_SUCCESS"
export const ASSIGN_OCCUPATION_DUTIES_FAIL = "ASSIGN_OCCUPATION_DUTIES_FAIL"

export const UNASSIGN_OCCUPATION_DUTIES = "UNASSIGN_OCCUPATION_DUTIES"
export const UNASSIGN_OCCUPATION_DUTIES_SUCCESS =
  "UNASSIGN_OCCUPATION_DUTIES_SUCCESS"
export const UNASSIGN_OCCUPATION_DUTIES_FAIL = "UNASSIGN_OCCUPATION_DUTIES_FAIL"

export const RESET_DUTIES_RESPONSES = "RESET_DUTIES_RESPONSES"

export const GET_AVAILABLE_DUTIES = "GET_AVAILABLE_DUTIES"
export const GET_AVAILABLE_DUTIES_SUCCESS = "GET_AVAILABLE_DUTIES_SUCCESS"
export const GET_AVAILABLE_DUTIES_FAIL = "GET_AVAILABLE_DUTIES_FAIL"

export const SELECT_DUTY_ROW = "SELECT_DUTY_ROW"
export const UNSELECT_DUTY_ROW = "UNSELECT_DUTY_ROW"
export const RESET_SELECTED_DUTY_ROWS = "RESET_SELECTED_DUTY_ROWS"

export const GET_POSITION_DUTIES = "GET_POSITION_DUTIES"
export const GET_POSITION_DUTIES_SUCCESS = "GET_POSITION_DUTIES_SUCCESS"
export const GET_POSITION_DUTIES_FAIL = "GET_POSITION_DUTIES_FAIL"
