export const GET_ASSIGNED_PSB_MEMBERS = "GET_ASSIGNED_PSB_MEMBERS"
export const GET_ASSIGNED_PSB_MEMBERS_SUCCESS =
  "GET_ASSIGNED_PSB_MEMBERS_SUCCESS"
export const GET_ASSIGNED_PSB_MEMBERS_FAIL = "GET_ASSIGNED_PSB_MEMBERS_FAIL"

export const GET_UNASSIGNED_PSB_MEMBERS = "GET_UNASSIGNED_PSB_MEMBERS"
export const GET_UNASSIGNED_PSB_MEMBERS_SUCCESS =
  "GET_UNASSIGNED_PSB_MEMBERS_SUCCESS"
export const GET_UNASSIGNED_PSB_MEMBERS_FAIL = "GET_UNASSIGNED_PSB_MEMBERS_FAIL"

export const GET_PSB_SUMMARY = "GET_PSB_SUMMARY"
export const GET_PSB_SUMMARY_SUCCESS = "GET_PSB_SUMMARY_SUCCESS"
export const GET_PSB_SUMMARY_FAIL = "GET_PSB_SUMMARY_FAIL"

export const GET_SELECTED_BY_APPOINTING_AUTHORITY =
  "GET_SELECTED_BY_APPOINTING_AUTHORITY"
export const GET_SELECTED_BY_APPOINTING_AUTHORITY_SUCCESS =
  "GET_SELECTED_BY_APPOINTING_AUTHORITY_SUCCESS"
export const GET_SELECTED_BY_APPOINTING_AUTHORITY_FAIL =
  "GET_SELECTED_BY_APPOINTING_AUTHORITY_FAIL"

export const GET_PSB_CBI_REPORTS_HEADER = "GET_PSB_CBI_REPORTS_HEADER"
export const GET_PSB_CBI_REPORTS_HEADER_SUCCESS =
  "GET_PSB_CBI_REPORTS_HEADER_SUCCESS"
export const GET_PSB_CBI_REPORTS_HEADER_FAIL = "GET_PSB_CBI_REPORTS_HEADER_FAIL"

export const GET_PSB_CBI_REPORTS = "GET_PSB_CBI_REPORTS"
export const GET_PSB_CBI_REPORTS_SUCCESS = "GET_PSB_CBI_REPORTS_SUCCESS"
export const GET_PSB_CBI_REPORTS_FAIL = "GET_PSB_CBI_REPORTS_FAIL"
// --------------------------------------------------------------------------------------------
export const ADD_PSB_MEMBER_TO_TABLE = "ADD_PSB_MEMBER_TO_TABLE"
export const REMOVE_PSB_MEMBER_FROM_TABLE = "REMOVE_PSB_MEMBER_FROM_TABLE"
export const RESET_PSB_MEMBERS_TABLE = "RESET_PSB_MEMBERS_TABLE"

export const ADD_PSB_MEMBER_TO_OPTIONS = "ADD_PSB_MEMBER_TO_OPTIONS"
export const REMOVE_PSB_MEMBER_FROM_OPTIONS = "REMOVE_PSB_MEMBER_FROM_OPTIONS"

export const SET_PSB_ROLES = "SET_PSB_ROLES"
export const ADD_PSB_ROLE_TO_OPTIONS = "ADD_PSB_ROLE_TO_OPTIONS"
export const REMOVE_PSB_ROLE_FROM_OPTIONS = "REMOVE_PSB_ROLE_FROM_OPTIONS"
