export const GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT =
  'GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT'
export const GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS =
  'GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS'
export const GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL =
  'GET_ALL_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL'

export const GET_ASSIGNABLE_EMPLOYEES = 'GET_ASSIGNABLE_EMPLOYEES'
export const GET_ASSIGNABLE_EMPLOYEES_SUCCESS =
  'GET_ASSIGNABLE_EMPLOYEES_SUCCESS'
export const GET_ASSIGNABLE_EMPLOYEES_FAIL = 'GET_ASSIGNABLE_EMPLOYEES_FAIL'

export const GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS =
  'GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS'
export const GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS_SUCCESS =
  'GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS_SUCCESS'
export const GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS_FAIL =
  'GET_EMPLOYEE_TEMPORARY_ASSIGNMENT_DETAILS_FAIL'

export const POST_EMPLOYEE_TEMPORARY_ASSIGNMENT =
  'POST_EMPLOYEE_TEMPORARY_ASSIGNMENT'
export const POST_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS =
  'POST_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS'
export const POST_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL =
  'POST_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL'

export const PATCH_EMPLOYEE_TEMPORARY_ASSIGNMENT =
  'UPDATE_EMPLOYEE_TEMPORARY_ASSIGNMENT'
export const PATCH_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS =
  'UPDATE_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS'
export const PATCH_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL =
  'UPDATE_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL'

export const DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT =
  'DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT'
export const DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS =
  'DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT_SUCCESS'
export const DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL =
  'DELETE_EMPLOYEE_TEMPORARY_ASSIGNMENT_FAIL'

export const RESET_EMPLOYEE_TEMPORARY_ASSIGNMENT_RESPONSE =
  'RESET_EMPLOYEE_TEMPORARY_ASSIGNMENT_RESPONSE'

export const GET_ALL_ORGANIZATIONS = 'GET_ALL_ORGANIZATIONS'
export const GET_ALL_ORGANIZATIONS_SUCCESS = 'GET_ALL_ORGANIZATIONS_SUCCESS'
export const GET_ALL_ORGANIZATIONS_FAIL = 'GET_ALL_ORGANIZATIONS_FAIL'
